### ISSUE TITLE
Asset library issue

### ISSUE THREAD

**Issue by Trey2k** [ashtonmeuser/godot-wasm#12]
Just wanted to let you know that you are effected by [this](https://github.com/godotengine/godot/issues/75712). Pretty much the editor does not account for custom download urls and expects there to be a container folder with the commit hash name. SO it ignores all top level folders in the zip. I fixed this for luaAPI by adding a dummy container folder.

**Comment by ashtonmeuser** [comment]
Interesting. Thanks for the heads up. Seems like something Godot ought to fix on their end. Worst case, I'll wrap the artifact in another dir and create an Asset Library-specific release aaset.

**Comment by ashtonmeuser** [comment]
Fixed in [v0.2.1](https://github.com/ashtonmeuser/godot-wasm/releases/tag/v0.2.1-godot-4).
