### ISSUE TITLE
Web/HTML5 export using addon fails

### ISSUE THREAD

**Issue by ashtonmeuser** [ashtonmeuser/godot-wasm#15]
Using Godot Wasm as an addon, web exports fail. This is a limitation of Godot (see https://github.com/godotengine/godot/issues/12243). Exporting to web/HTML5 will require module support (see https://github.com/ashtonmeuser/godot-wasm/issues/7).

**Comment by fire** [comment]
Module support was now tested recently and revised. Can update the status?

**Comment by ashtonmeuser** [comment]
Closing this as web export will never be supported when Godot Wasm is used via addon. For web/HTML5 export using Godot Wasm as a module, see #18.

**Comment by nageslan** [comment]
Perhaps we could refer to LimboAI's approach. When I used the LimboAI plugin, I noticed that it supports web export.

**Comment by ashtonmeuser** [comment]
@nageslan this is a more complex issue than simple web exports via Godot GDExtension/GDNative addon. In addition, the Wasm runtime must be exportable to web. See #18 for more context.
