### ISSUE TITLE
🍎 macOS / Template (target=template_release) build failure

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#21]
See https://github.com/V-Sekai/godot/tree/wasm

Appears to be minor bug

```
modules/wasm/src/godot-wasm.cpp:53:26: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
        if (array.size() != results->size) return ERR_PARAMETER_RANGE_ERROR;
            ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/wasm/src/godot-wasm.macos.template_release.x86_64.o] Error 1
```

https://github.com/V-Sekai/godot/actions/runs/4867601731/jobs/8680337459

**Comment by ashtonmeuser** [comment]
Fixed in https://github.com/ashtonmeuser/godot-wasm/commit/2ab686d34817919d6359cb3194a67cb8b3cd8b29 and https://github.com/ashtonmeuser/godot-wasm/commit/6a4ca7008e78483bc11c14a1fe1769c459d99dfe for Godot 3.x and 4.x, respectively.
