### ISSUE TITLE
Auto download Wasmer libs for module use

### ISSUE THREAD

**Issue by ashtonmeuser** [ashtonmeuser/godot-wasm#22]
Should download Wasmer libs (if required) when Godot Wasm used as a module i.e. in _SCsub_. Spawned from [this comment](https://github.com/ashtonmeuser/godot-wasm/issues/20#issuecomment-1532437317). This may be a good opportunity to abstract the Wasmer lib download functionality already present in _SConstruct_.

**Comment by fire** [comment]
You got the description of downloading Wasmer libraries correct. 

Also note that windows supports both mingw and mvsc which corresponds .a and lib.

**Comment by fire** [comment]
Fails here:

https://github.com/V-Sekai/godot/actions/runs/4867601731/jobs/8680337146

![image](https://user-images.githubusercontent.com/32321/236052596-4958e709-f651-4783-bdf0-c3b04b63bbd7.png)

Trying to get more screenshots

**Comment by ashtonmeuser** [comment]
Pushed a fix in https://github.com/ashtonmeuser/godot-wasm/commit/aa4b49edc2bceafe229b559e23ca71ceac9ae7eb (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/e6bb0ee8ee2f0583295d73d23c4afa74c076a3f8 (Godot 4.x). The issue was that the Wasmer library wasn't being downloaded for the `linuxbsd` platform specified by Godot modules. The library download and default version are also now kept in a common file (_utils.py_) which should simplify maintaining the two branches.

Also addresses using a `.a` library suffix for MinGW. Note that the MVSC suffix is actually `.dll.lib` which seems to be specific for Wasmer.

@fire Lemme know if this will suffice and I'll close this issue.

**Comment by ashtonmeuser** [comment]
This made me realize that the paths for Linux in the actual GDExtension file will probably be incorrect (should be `.../linuxbsd/...` instead of `.../linux/...`). Should compile but won't run. Away from my computer and can't fix right now. Just a heads up.

**Comment by fire** [comment]
Doing a test now. Will edit the issue.

**Comment by fire** [comment]
Some errors. I added a fix for the lib download but failing elsewhere.

![image](https://user-images.githubusercontent.com/32321/236149803-84098457-95d3-4d6e-8342-99214e6d932d.png)

**Comment by ashtonmeuser** [comment]
Created #26 to capture failing MinGW build.

**Comment by ashtonmeuser** [comment]
@fire Huge thanks for all of the feedback you've provided! I think I've addressed everything you mentioned. All outstanding tasks have been rolled into their own issues seeing as we've gone on a bit of a tangent here. Let me know if anything's been missed.

**Comment by fire** [comment]
I'm a bit tired, so I'll let you know when I do an update.

I believe you can use a hot patch on the wasmer includes. Like literally apply a diff.

**Comment by fire** [comment]
We can close this one though.

**Comment by ashtonmeuser** [comment]
No rush at all! Yeah I'm sure there are plenty of workarounds but figured I'd open a PR in case others faced the same issue. Closing this.
