### ISSUE TITLE
module/wasm missing documentation

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#24]
Add docs generated by `--doctool` to 

* `modules/wasm/doc/classes/StreamPeerWasm.xml`
* `modules/wasm/doc/classes/Wasm.xml`

Modify config.py to add the class documentation folder. See https://github.com/V-Sekai/many_bone_ik/blob/master/config.py

```
Running --doctool to see if this changes the public API without updating the documentation.
If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.


WARNING: Instantiated StreamPeerWasm used as default value for Wasm's "stream" property.
     at: class_get_default_property_value (core/object/class_db.cpp:1517)
New doc file missing in PR: doc/classes/StreamPeerWasm.xml
New doc file missing in PR: doc/classes/Wasm.xml
Error: Process completed with exit code 1.
```

**Comment by fire** [comment]
See https://github.com/ashtonmeuser/godot-wasm/pull/25

**Comment by ashtonmeuser** [comment]
@fire Merged #25 and added basic documentation in https://github.com/ashtonmeuser/godot-wasm/commit/e8a539a2355da8b3cb2bdc15a86561b6321f28ff (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/5f5fbda8b9866b057a023a255d5c088f9e9f2c16 (Godot 4.x).

**Comment by ashtonmeuser** [comment]
Reopening because docs seem to not be generating correctly despite descriptions existing for all methods. Investigating.

<img width="886" alt="Screen Shot 2023-05-04 at 7 34 46 PM" src="https://user-images.githubusercontent.com/7253863/236366790-b0ebcdfa-935e-4bd8-aa21-60faf55c3371.png">

**Comment by ashtonmeuser** [comment]
Fixed. `param` XML element should be `argument` for Godot 3.x.
