### ISSUE TITLE
MinGW Windows build fails

### ISSUE THREAD

**Issue by ashtonmeuser** [ashtonmeuser/godot-wasm#26]
Requires a change to Wasmer. Spawned from [this comment](https://github.com/ashtonmeuser/godot-wasm/issues/22#issuecomment-1534289750). Dependent on https://github.com/wasmerio/wasmer/pull/3849. Also see https://github.com/WebAssembly/wasm-c-api/pull/182.

**Comment by fire** [comment]
Can we run a hotpatch process on download? I don't know how long it'll take and I'd like to integrate godot-wasm this weekend into our build system.

**Comment by ashtonmeuser** [comment]
Yessir. Hotpatch applied in https://github.com/ashtonmeuser/godot-wasm/commit/d8d7f0ec78a86bb1d4497fa30556068c30ba8c7f (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/a41d27d433f18c7d086e5e33f1daf1b5bf16c351 (Godot 4.x). Closing this but will loop back once upstream changes land.

**Comment by fire** [comment]
Awesome!

I really appreciate your work.

**Comment by fire** [comment]
@ashtonmeuser I think patch might not exist but `git patch` might

**Comment by ashtonmeuser** [comment]
> I really appreciate your work.

Right back at ya! This project has been massively improved by your feedback!

> I think patch might not exist but git apply might. We are assuming git exists.

Huh I was kinda under the assumption that [patch](https://man7.org/linux/man-pages/man1/patch.1.html) would be a safer assumption in an environment using MinGW and would work outside of a repo. We could always hedge our bets with `if [ $(command -v patch) ]; then patch -p1 < wasm-mingw.patch; else git apply wasm-mingw.patch; fi`.
