### ISSUE TITLE
Linking `userenv` is failing

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#27]
I have no idea why. https://github.com/V-Sekai/godot/actions/runs/4897415488/jobs/8745444818

`userenv` is failing.

https://user-images.githubusercontent.com/32321/236567536-dd3a5a1c-d9e0-4c7d-81cf-4cd23b9dde88.png

![image](https://user-images.githubusercontent.com/32321/236567536-dd3a5a1c-d9e0-4c7d-81cf-4cd23b9dde88.png)

**Comment by fire** [comment]
```
elif env["platform"] == "windows":
    env["LIBWASMERSUFFIX"] = ".a" if env.get("use_mingw") else ".dll.lib"
    if env.get("use_mingw"):
        env.Append(LIBS=["userenv"])
    else:
        env.Append(LIBS=["Userenv"])
```

Maybe fixes this?

**Comment by ashtonmeuser** [comment]
I'll dig out my dusty old Windows machine and investigate this. Haven't even taken a look but if you've got the time, try using the libraries used in _SConstruct_.

**Comment by fire** [comment]
'userenv.windows.template_release.x86_64.lib' is not a valid library name

**Comment by ashtonmeuser** [comment]
Sounds like it's using the library suffix inherited from Godot when it shouldn't be. Can we define it explicitly with `env.File()`?

The only reason this lib was included is [this comment](https://github.com/ashtonmeuser/godot-wasm/issues/22#issuecomment-1534297000). What happens if we just drop it for MSVC builds?

**Comment by fire** [comment]
I won't be able to use godot-wasm then because our builds use llvm-mingw.

**Comment by ashtonmeuser** [comment]
Sorry still out and about so just spitballing here. I'll take a closer look shortly. I'm definitely not saying we drop your use case! We'll figure it out!

**Comment by fire** [comment]
I think your suggestion worked, when https://github.com/V-Sekai/godot/actions/runs/4899298148/jobs/8749165531 finishes I 'll try to pr.

**Comment by fire** [comment]
Oh no. Apparently wasmer uses a .dll. Will have to investigate making it a static link later

**Comment by ashtonmeuser** [comment]
Amazing! Thanks for doing the legwork here. Feel free to open a similar PR against master for that long overdue contributor credit. Otherwise, I'll cherrypick.

**Comment by fire** [comment]
Closing because issue is resolved.

**Comment by ashtonmeuser** [comment]
Likely related to https://github.com/godotengine/godot/issues/23687. The same issue doesn't affect GDNative/GDExtension addons because I'm overwriting `env["LIBSUFFIX"]` in _SConstruct_. Hesitant to do the same thing in _SCsub_ as it would be applied to the engine's `env`. Looking into this further.

**Comment by ashtonmeuser** [comment]
This seems like a deficiency of Godot and possibly Scons. Godot changing `LIBSUFFIX` seems pretty heavy handed and basically precludes modules from using Windows SDK libs. 

That said, I've got an idea for a workaround involving Scons [`AddPreAction`](https://scons.org/doc/2.2.0/HTML/scons-user/a11700.html). This is run after compilation but before linking. Should be able to parse the auto-generated [`_LIBFLAGS`](https://scons.org/doc/0.97/HTML/scons-user/a3414.html#CV-_LIBFLAGS) and edit Windows SDK lib names.

**Comment by ashtonmeuser** [comment]
I went with the **Ugly Fuck It Solution™** and added the Windows SDK libs directly to `LINKFLAGS` for MSVC builds which is explicitly recommended against by SCons. I'm sure there's a really clever workaround here but this'll do. This is well into the territory of a kludgy Godot idiosyncrasy. 

@fire Give it a shot! I've also created #33 to eventually remove dependence on your Godot fork (which has been super helpful ❤️) and provide the engine with Godot Wasm baked in as a module.

**Comment by fire** [comment]
Testing now. Wait an hour :'(

**Comment by ashtonmeuser** [comment]
I'd love to know why Godot 4 builds so much slower.

**Comment by fire** [comment]
Cache doesn't work well when the build never succeeds because it starts from the last cache. (which is empty)

**Comment by fire** [comment]
Hype! The game template passed.

**Comment by fire** [comment]
Passed. 🎉

**Comment by ashtonmeuser** [comment]
> Cache doesn't work well when the build never succeeds because it starts from the last cache.

Great point! Woooooooooooo I see green 🎉🎉🎉 Next builds should be a little faster! Thanks so much for all your help with this!
