### ISSUE TITLE
Validate all use cases and platforms

### ISSUE THREAD

**Issue by ashtonmeuser** [ashtonmeuser/godot-wasm#31]
As this project inches closer to stability, it'll be helpful to test on each platform and under each usage case. Formal tests are the ideal but at least this will serve as proof of things working at a given point in time. Should test with the _Wasm Consume_ example project which uses most functionality of Godot Wasm.

I'll update the following as testing happens.

Use Case | Linux| macOS | Windows (MVSC) | Windows (MinGW)
-|:-:|:-:|:-:|:-:
GDNative addon | ✅ [6db146b](https://github.com/ashtonmeuser/godot-wasm/commit/6db146b1f2b03457937ac9bd209a4dfb17dc931c) | ✅ [29356da](https://github.com/ashtonmeuser/godot-wasm/commit/29356da3fbbffe2d33f7210c7742d699178a867d) | ✅ [29356da](https://github.com/ashtonmeuser/godot-wasm/commit/29356da3fbbffe2d33f7210c7742d699178a867d) | 🚫
GDExtension addon | ✅ [f2b1cc3](https://github.com/ashtonmeuser/godot-wasm/commit/f2b1cc3bb2dc254d21f62c4228be8dc1cd8bbaa0) | ✅ [2999e89](https://github.com/ashtonmeuser/godot-wasm/commit/2999e89a5f65e91625ad7a728c318b577439b98b) | ✅ [2999e89](https://github.com/ashtonmeuser/godot-wasm/commit/2999e89a5f65e91625ad7a728c318b577439b98b) | 🚫
Godot 3 module | ✅ [eea765c](https://github.com/ashtonmeuser/godot-wasm/commit/eea765c5fda78ec6309865243a62448af244ec0b) | ✅ [29356da](https://github.com/ashtonmeuser/godot-wasm/commit/29356da3fbbffe2d33f7210c7742d699178a867d) | ✅ [6db146b](https://github.com/ashtonmeuser/godot-wasm/commit/6db146b1f2b03457937ac9bd209a4dfb17dc931c) | ❌ [2a56e2c](https://github.com/ashtonmeuser/godot-wasm/commit/2a56e2ce85fbb3810b9e08a5e8e6c78f1083ca8a)
Godot 4 module | ✅ [f2b1cc3](https://github.com/ashtonmeuser/godot-wasm/commit/f2b1cc3bb2dc254d21f62c4228be8dc1cd8bbaa0) | ✅ [2999e89](https://github.com/ashtonmeuser/godot-wasm/commit/2999e89a5f65e91625ad7a728c318b577439b98b) | ✅ [f2b1cc3](https://github.com/ashtonmeuser/godot-wasm/commit/f2b1cc3bb2dc254d21f62c4228be8dc1cd8bbaa0) | ❌ [6114faf](https://github.com/ashtonmeuser/godot-wasm/commit/6114faf57b31ceb53a3c72dbec4f6d07e6e26c60)

⏱️ Pending &nbsp;&nbsp;&nbsp; ✅ Success &nbsp;&nbsp;&nbsp; ❌ Failure &nbsp;&nbsp;&nbsp; 🚫 Unsupported

**Comment by fire** [comment]
What is blocking mingw validation?

**Comment by ashtonmeuser** [comment]
@fire Nothing besides my lack of time. We need a new workflow similar to the other three that build the addon for Windows using MinGW. Note that this would be purely for peace of mind as it's not needed in the release artifact (we've got a Windows binary already via MVSC).

**Comment by ashtonmeuser** [comment]
There is no mention of MinGW or a `use_mingw` option in the Godot C++ bindings [GDExtension Sconstruct](https://github.com/godotengine/godot-cpp/blob/master/SConstruct) (inherited by the [Godot Wasm 4.x Sconstruct](https://github.com/ashtonmeuser/godot-wasm/blob/master/SConstruct)) or the [GDNative Sconstruct](https://github.com/godotengine/godot-cpp/blob/3.x/SConstruct) files. Further, at the time of writing, there is no `use_mingw` option in the [Godot Wasm 3.x Sconstruct](https://github.com/ashtonmeuser/godot-wasm/blob/godot-3/SConstruct) (which does _not_ inherit from Godot C++ bindings GDNative Sconstruct). All of this means that, henceforth, building the Godot Wasm GDExtension/GDNative addon with MinGW will not be supported.

**Comment by fire** [comment]
I will still attempt to build with mingw and send the results thought.On Jun 26, 2023, at 4:32 PM, Ashton Meuser ***@***.***> wrote:﻿
There is no mention of MinGW or a use_mingw option in the Godot C++ bindings GDExtension Sconstruct (inherited by the Godot Wasm 4.x Sconstruct) or the GDNative Sconstruct files. Further, at the time of writing, there is no use_mingw option in the Godot Wasm 3.x Sconstruct (which does not inherit from Godot C++ bindings GDNative Sconstruct). All of this means that, henceforth, building the Godot Wasm GDExtension/GDNative addon with MinGW will not be supported.

**Comment by ashtonmeuser** [comment]
That would be super helpful! I'd love to close this issue.

Cross compiling using MinGW on Linux fails with the following errors (truncated). Seems like more issues related to Windows SDK includes.
```
/usr/bin/x86_64-w64-mingw32-ld: modules/wasm/wasmer/lib/libwasmer.a(std-63790cb7e7741ec2.std.274b4a81-cgu.0.rcgu.o): in function `std::sys::windows::os::home_dir_crt::{{closure}}':
/rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys\windows/os.rs:298: undefined reference to `GetUserProfileDirectoryW'
/usr/bin/x86_64-w64-mingw32-ld: modules/wasm/wasmer/lib/libwasmer.a(std-63790cb7e7741ec2.std.274b4a81-cgu.0.rcgu.o): in function `std::sys::windows::net::Socket::shutdown':
/rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys\windows/net.rs:383: undefined reference to `shutdown'
/usr/bin/x86_64-w64-mingw32-ld: modules/wasm/wasmer/lib/libwasmer.a(std-63790cb7e7741ec2.std.274b4a81-cgu.0.rcgu.o): in function `std::sys_common::net::getsockopt':
/rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common/net.rs:82: undefined reference to `getsockopt'
/usr/bin/x86_64-w64-mingw32-ld: /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common/net.rs:82: undefined reference to `getsockopt'
/usr/bin/x86_64-w64-mingw32-ld: modules/wasm/wasmer/lib/libwasmer.a(std-63790cb7e7741ec2.std.274b4a81-cgu.0.rcgu.o): in function `std::sys_common::net::getsockopt':
/rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common/net.rs:82: undefined reference to `getsockopt'
```

**Comment by fire** [comment]
To be honest I wasn't debugging this because I wasn't sure if the Ref<Script> thing for wasm was being worked on.

Also the I've been consistently said I was testing with mingw-llvm which is not gcc mingw.

**Comment by fire** [comment]
From the point of view of project management I would close this issue and add a new issue for llvm-mingw.

**Comment by ashtonmeuser** [comment]
> I wasn't sure if the Ref<Script> thing for wasm was being worked on.
Still being worked on but alongside other tasks. At the top of the list is testing (which is [getting close](https://github.com/ashtonmeuser/godot-wasm/pull/46)) so I can release with more confidence.

> I was testing with mingw-llvm which is not gcc mingw.
Ah good point. Does this support cross compiling to Windows from Linux? Are you building on Windows? 

> I would close this issue and add a new issue.
Good call. I'll do this if I don't make any progress this evening.

**Comment by ashtonmeuser** [comment]
Closing this. I'm not confident MinGW will build and at this point, don't have the time to focus on it. There are successful builds for the three supported platforms (Linux, macOS, Windows) which will have to suffice for the time being.
