### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#34]
📊 Static checks / Code style, file formatting, and docs: modules/wasm/doc_classes/Wasm.xml#L54
specifiying ==> specifying

**Comment by ashtonmeuser** [comment]
Fixed in https://github.com/ashtonmeuser/godot-wasm/commit/822aa341cba8dd40b16bd7cd1e233af2a91e1061 (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/08c0927412efafa2f5aeea23736b53e2f2fea301 (Godot 4.x). Thanks for pointing out!
