### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by ashtonmeuser** [ashtonmeuser/godot-wasm#6]

**Comment by Trey2k** [comment]
Still a WIP but you can see the godot 4 support I am working on [here](https://github.com/Trey2k/godot-wasm/commits/godot-4). Currently it builds as a module and extension. I still need to add support for 32 bit packed int and float arrays. As well as general testing. If you have any comments on it let me know.

**Comment by ashtonmeuser** [comment]
Looks like a good start! Left a few comments. At such an early stage in this project, I think our biggest enemy will be drift between the two branches in active dev. Anything that stems that would probably save headaches in the future. Hope you're okay with a few upcoming refactors.

**Comment by Trey2k** [comment]
> Looks like a good start! Left a few comments. At such an early stage in this project, I think our biggest enemy will be drift between the two branches in active dev. Anything that stems that would probably save headaches in the future. Hope you're okay with a few upcoming refactors.

I fully suspect there to be some level of code drift. As more features are added to godot-wasm the API difference between 3 and 4 will become a lot more prevalent too. Any update to the gd3 version I suspect will be easier to handle as a separate update to gd4. I will do my best to keep up though as I plan on using wasm with godot 4.

**Comment by Trey2k** [comment]
With the recent changes in mind, im planning on just redoing the godot 4 conversion this weekend from master. I feel its going to be a lot simpler then attempting a marge. So can we merge the current master into the godot-4 branch?

**Comment by ashtonmeuser** [comment]
I think that's wise. There were no changes to the `godot-4` branch so fast-forwarded it to [v0.1.6](https://github.com/ashtonmeuser/godot-wasm/releases/tag/v0.1.6). Thanks for the effort and let me know if I can help and/or make things easier going forward.

**Comment by Trey2k** [comment]
Small update, ive finished most of the work at this point but ran into issues with the stream peer. That API has changed a lot. Not sure if I will end up finishing it this weekend as I got a lot going on. But hopefully should be done soon.

**Comment by ashtonmeuser** [comment]
Awesome! Thanks again for the effort. I found some time this weekend to include support for import functions. Check out https://github.com/ashtonmeuser/godot-wasm/pull/14. Shouldn't significantly hamper the Godot 4 work but let me know your thoughts or if I can help.

**Comment by ashtonmeuser** [comment]
@Trey2k found some time this weekend to add Godot 4 support. Check out the [Godot 4 release](https://github.com/ashtonmeuser/godot-wasm/releases/tag/v0.1.8-godot-4) and [Godot 4 branch](https://github.com/ashtonmeuser/godot-wasm/tree/godot-4). More than happy to hear any and all feedback.

I tried to align the master branch as much as possible which made for a pretty [minimal difference](https://github.com/ashtonmeuser/godot-wasm/compare/v0.1.8-godot-3...v0.1.8-godot-4). Should be able to merge upstream changes back or rebase entirely pretty easily.

**Comment by Trey2k** [comment]
> @Trey2k found some time this weekend to add Godot 4 support. Check out the [Godot 4 release](https://github.com/ashtonmeuser/godot-wasm/releases/tag/v0.1.8-godot-4) and [Godot 4 branch](https://github.com/ashtonmeuser/godot-wasm/tree/godot-4). More than happy to hear any and all feedback.
> 
> I tried to align the master branch as much as possible which made for a pretty [minimal difference](https://github.com/ashtonmeuser/godot-wasm/compare/v0.1.8-godot-3...v0.1.8-godot-4). Should be able to merge upstream changes back or rebase entirely pretty easily.

Awesome! Ive been very busy recently so was not able to make the progress I wanted to. Looks good!
